function augment_all_categories()

categories = {'basketball_layup', ...
              'bowling', ...
              'clean_and_jerk', 'discus_throw', ...
              'diving_platform_10m', 'diving_springboard_3m', 'hammer_throw', ...
              'high_jump', 'javelin_throw', 'long_jump', ...
              'pole_vault', 'shot_put', 'snatch', 'tennis_serve', 'triple_jump', ...
              'vault'};

for i = 1:length(categories)
    fprintf('--------CAT %d -------------\n', i);
    augment_patches_distr(categories{i});
end

end

    